[package]
name = "platformer-game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.1"
bevy_asset_loader = "0.20"  # For asset loading
avian2d = "0.2.1"
bevy_light_2d = "0.5.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
